### PR TITLE
Update and Correct README with many things

### PR DESCRIPTION
**Pull request by DJZSwag**
Change order is from top to bottom.
-Updated install instructions for Pojlib QCXR (Not Pojav)
-Added an included mods list, as to:
1. Not make players accidentally place duplicates of .jars and potentially prevent MC from loading. 
2. Provide information on the mods bundled (NOTE: All mods were based off of the mods.json in the Pojlib repo) 
-Changed Recommended Mods to include some more useful but optional mods, replacing the ones that are already bundled in 
-Changed credits to include the Vivecraft Fabric port instead of MCXR, but kept the link and credits because I'm a nice person  
-Removed Sodium from the Incompatible mods part (Below the recommended mod list)
-That's it!

### CODE REVIEW

**Comment by DJZSwag** [comment]
I noticed that I may have accidentally deleted the building part. Doesn't matter too much (I think?).

**Comment by thejudge156** [comment]
Yeah, building is not needed, as we no longer support building our launcher. Pojlib can be built but that’s about it. I will merge this soon probably.

**Comment by DJZSwag** [comment]
I may create an FAQ section to address some common concerns with QCXR. I wonder if I should make this apart of the README or its own doc.

**Comment by DJZSwag** [comment]
Question: Is Distant Horizons support planned?

**Comment by DJZSwag** [comment]
Never mind. There aren't that many relevant questions to answer. Im just going to put them in Notes.

**Comment by DJZSwag** [comment]
Just checked more of your repos, and I realized that the Sodium repo hasnt been updated for almost a year. It may be useless to keep the text, especially since we have full(?) support for Sodium now.

**Comment by DJZSwag** [comment]
I forgot to add that I have made a sentence for people who will probably ask for pico support.

**Comment by thejudge156** [comment]
> Just checked more of your repos, and I realized that the Sodium repo hasnt been updated for almost a year. It may be useless to keep the text, especially since we have full(?) support for Sodium now.

Yeah, we need to delete it.

**Comment by thejudge156** [comment]
> Question: Is Distant Horizons support planned?

If we can get a new renderer yes.

**Comment by DJZSwag** [comment]
Aight, that’s all from me. Good time committing to this repo. I await the merge.

**Comment by DJZSwag** [comment]
AND THE PR… IS… MEEERRRGED!!!!!
rogan

**Pull request merged**
