### PR TITLE
Create questcraft

### PR DESCRIPTION
**Pull request by 7o1425**

### CODE REVIEW

**Comment by Flamgop** [comment]
Why??

**Comment by Dogey11** [comment]
> Why??

These people think they need a github account to use QuestCraft, IIRC github prompts new users to make their first repo, pull request etc.

**Comment by D2Lx0wse** [comment]
> > Why??
> 
> These people think they need a github account to use QuestCraft, IIRC github prompts new users to make their first repo, pull request etc.

I can't believe this

**Comment by wellsilver** [comment]
> 
> I can't believe this

its what happens when you make it semi-complicated to install something young children will use

**Comment by D2Lx0wse** [comment]
> > I can't believe this
> 
> its what happens when you make it semi-complicated to install something young children will use

Well the kid doesn't need to register to GitHub

**Comment by wellsilver** [comment]
> > > I can't believe this
> > 
> > 
> > its what happens when you make it semi-complicated to install something young children will use
> 
> Well the kid doesn't need to register to GitHub

yes

**Pull request closed without merging**
