### PR TITLE
adjusting swags servers.

### PR DESCRIPTION
**Pull request by DED0026**
mcvr domain is dead and as of yet not back online, replaced it with ross light network.
added the bones network at the bottom.
changed "Recommended servers" to "Known compatible"

### CODE REVIEW

**Comment by BonesMgee** [comment]
:trollface:

**Comment by DED0026** [comment]
YIPPIEE

**Comment by swaggio7** [comment]
Sorry for the servers. i shall scold the one responsible

**Comment by DiveaLism** [comment]
-_-

**Pull request merged**
