### PR TITLE
YetAnotherREADMEUpdate

### PR DESCRIPTION
**Pull request by swaggio7**
I'm officially declaring myself a README enthusiast. Quick question, do I add the mods authors' names in the next README update? 
-Made SideQuest's Recommended text bold because it's the best way to install QuestCraft 
-Added Debugify and Memory Leak Fix
-Added 2 ways to configure mods
-Fixed some grammar

### CODE REVIEW

**Comment by swaggio7** [comment]
I await ze merge

**Comment by CADIndie** [comment]
Please remove QuestToolbox (GH won't let me edit the PR for some reason).

I think we should leave just the links for the mods as adding authors will clutter the README more then it already is.

**Comment by swaggio7** [comment]
Aight. That's all.

**Comment by swaggio7** [comment]
Shoot, dont merge.

**Comment by swaggio7** [comment]
That's all from me (for now). Ima sleep.

**Pull request merged**
