### PR TITLE
Fixing carts terrible grammar :3

### PR DESCRIPTION
**Pull request by thewiilover**
Because he is too lazy to fix it himself:3

### CODE REVIEW

**Comment by KitchenBoy08** [comment]
Nuh uh still grammatically incorrect :333

**Comment by thewiilover** [comment]
> Nuh uh still grammatically incorrect :333

If you think it's grammatically incorrect then you need to go back to school. :3

**Comment by computer-catt** [comment]
that's very mean, respect the efforts of other contributors

**Comment by KitchenBoy08** [comment]
I just joking, too tired to tell if that's satire or not lmao
my bad

**Comment by computer-catt** [comment]
> I just joking, too tired to tell if that's satire or not lmao
> my bad

i was referring to the wii lover

**Pull request merged**
